config/routes.rb
# require 'sidekiq/web'
Rails.application.routes.draw do

  # mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app

  get 'search', to: 'search#index'

  # config/routes.rb
  resources :subscriptions, only: [:new, :create] do
    post 'pause', on: :member
    post 'resume', on: :member
  end

  devise_for :users
  resources :catagories
  resources :posts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # 
  resources :posts do
    resources :comments do
      post 'reply', on: :member
    end
  end

  resources :catagories do
    resources :posts
  end

  resources :users do
    resources :posts
  end

  get 'landingpage', to: 'posts#landingpage', as: 'landingpage'

  root to: "posts#index"

  resources :posts do
    member do
      get :expand_overview
    end
  end




end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post


  validates :commenter, presence: true
  validates :body, presence: true

  belongs_to :parent, class_name: "Comment", optional: true  # yeh comment ke parent ko reference karta hai
  has_many :children, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post



  def create
    @comment = @post.comments.build(comment_params)
    if @comment.save
      redirect_to @post, notice: 'Your comment was successfully posted.'
    else
      render 'posts/show', alert: 'There was an error posting your comment.'
    end
  end

  def reply
    @parent_comment = Comment.find(params[:parent_comment_id])
    @comment = @parent_comment.children.build(comment_params)
    if @comment.save
      redirect_to @post, notice: 'Your reply was posted successfully.'
    else
      render 'posts/show', alert: 'There was an error posting your reply.'
    end
  end


  def update
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_comment_path(@post, @comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: post_comment_path(@post, @comment) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to @post, notice: "Comment was successfully deleted." }
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove(@comment)
      end
    end



  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment " id="comment_<%= comment.id %>">
    <p><%= comment.body %></p>
    <p><%= time_ago_in_words(comment.created_at) %> ago</p>

<!--not working properly-->
<!--    <div class="d-flex gap-2">-->
      <%# if user_signed_in? && (current_user.admin? || @post.user == current_user) %>
        <%#= link_to 'Edit', edit_post_comment_path(comment), class: 'btn btn-secondary' %>
        <%#= button_to 'Delete', post_comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      <%# end %>
<!--    </div>-->

  <!-- Render replies to this comment (if any) -->
  <% if comment.children.any? %>
    <div class="replies">
      <% comment.children.each do |child_comment| %>
        <%= render 'comment', comment: child_comment %>
      <% end %>
    </div>
  <% end %>

  <!-- Form to reply to this comment -->
  <%#link_to "Reply Comment", reply_post_comment_path, comment: comment %>
  <%= render 'comments/reply_form', comment: comment %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
  <div class="container">
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  </div>
<% end %>

app/views/comments/_reply_form.html.erb
<%= form_with(model: [ @post, comment.children.build ], local: true) do |form| %>
  <div class="container">
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="container">
    <h1>Edit Comment</h1>
    <%= render "comments/form"%>
</div>