config/routes.rb
# require 'sidekiq/web'
Rails.application.routes.draw do

  # mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app

  get 'search', to: 'search#index'

  # config/routes.rb
  resources :subscriptions, only: [:new, :create] do
    post 'pause', on: :member
    post 'resume', on: :member
  end

  devise_for :users
  resources :catagories
  resources :posts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # 
  resources :posts do
    resources :comments do
      post 'reply', on: :member
    end
  end

  resources :catagories do
    resources :posts
  end

  resources :users do
    resources :posts
  end

  get 'landingpage', to: 'posts#landingpage', as: 'landingpage'

  root to: "posts#index"

  resources :posts do
    member do
      get :expand_overview
    end
  end




end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :body
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :catagory
  has_one_attached :cover_image

  enum status: {
    draft: 0,
    pending: 1,
    published: 2,
    rejected: 3
  }

  validates :catagory, presence: true
  validates :cover_image, presence: true
  validates :title, presence: true
  validates :overview, presence: true, length: { maximum: 300 }
  validates :body, presence: true, length: { minimum: 250 }



  def self.ransackable_associations(auth_object = nil)
    ["catagory", "comments", "cover_image_attachment", "cover_image_blob", "rich_text_body", "user"]
  end

  # List of attributes that Ransack can search
  def self.ransackable_attributes(auth_object = nil)
    ["body", "catagory_id", "created_at", "id", "id_value", "overview", "status", "title", "updated_at", "user_id"]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ApplicationHelper
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_non_admin_users, only: [:index]

  

  # GET /posts or /posts.json
  # def index
  #   if params[:user_id]
  #     @user = User.find_by(id: params[:user_id])
  #     if @user
  #       @pagy, @posts = pagy(@user.posts)
  #     else
  #       flash[:alert] = "User not found"
  #       @pagy, @posts = pagy(Post.all, items: 5)
  #     end
  #   elsif params[:catagory_id]
  #     @catagory = Catagory.find_by(id: params[:catagory_id])
  #     if @catagory
  #       @pagy, @posts = pagy(@catagory.posts)
  #     else
  #       flash[:alert] = "Category not found"
  #       @pagy, @posts = pagy(Post.all, items: 5)
  #     end
  #   else
  #     if user_signed_in?
  #       if current_user.admin?
  #         @pagy, @posts = pagy(Post.all, items: 5)
  #       else
  #         @pagy, @posts = pagy(current_user.posts)
  #       end
  #     else
  #       @pagy, @posts = pagy(Post.all, items: 5)
  #     end
  #   end
  # end
  def index
    # @q = Post.ransack(params[:q])
    # @post = @q.result(distinct: true)
    #

    if params[:user_id]
      @user = User.find_by(id: params[:user_id])
      if @user
        @pagy, @posts = pagy(@user.posts, items: 3) # Set items per page to 3
      else
        flash[:alert] = "User not found"
        @pagy, @posts = pagy(Post.all, items: 3) # Default to 3 items
      end
    elsif params[:catagory_id]
      @catagory = Catagory.find(params[:catagory_id])
      @pagy, @posts = pagy(@catagory.posts, items: 3)
    else
      if user_signed_in?
        if current_user.admin?
          @pagy, @posts = pagy(Post.all, items: 3) # Default to 3 items for admin
        else
          @pagy, @posts = pagy(current_user.posts, items: 3)
        end
      else
        @pagy, @posts = pagy(Post.all, items: 3) # Default to 3 items for guests
      end
    end
    TestJob.perform_later("Hello from Sidekiq!")

  end
  
  def expand_overview
    @post = Post.find(params[:id])
    render partial: "post_card", locals: { post: @post }
  end
  

  def user_posts
    @users = User.find(params[:id])
    @posts = @users.posts
  end

  def landingpage
    
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # For regular requests
      format.turbo_stream # For Turbo Frame requests
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user=current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_path, status: :see_other, notice: "Post was successfully destroyed." }
      format.json { head :no_body }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body,:overview ,:cover_image, :status, :catagory_id,)
    end


    def set_non_admin_users
      @non_admin_users = User.where(admin: false)
    end



    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="container">
  <%= form_with(model: post) do |form| %>
    <% if post.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% post.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

   



    <div class="mb-3">
      <%= form.label :title, class: "form-label font-weight-bold", style: "font-size: 1.6rem;" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :overview, class: "form-label font-weight-bold", style: "font-size: 1.6rem;" %>
      <%= form.text_field :overview, class: "form-control" %>
    </div>

      <div class="mb-3">
      <%= form.label :cover_image, class: "form-label font-weight-bold", style: "font-size: 1.6rem;" %>
      <%= form.file_field :cover_image, class: "form-control" %>
    </div>'
    <div class="mb-3">
      <%= form.label :body, class: "form-label font-weight-bold", style: "font-size: 1.6rem;" %>
      <%= form.rich_text_area :body, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :status, class: "form-label font-weight-bold", style: "font-size: 1.6rem;" %>
      <%= form.select :status, Post.statuses.keys.map { |status| [status.titleize, status] }, { class: "form-select" } %>
    </div>

    <div class="mb-3">
      <%= form.label :catagory_id, "Category" , class: "form-label font-weight-bold", style: "font-size: 1.6rem;" %>
      <%= form.collection_select :catagory_id, Catagory.all, :id, :name, prompt: true %>
    </div>

    <div>
      <%= form.submit class: "btn btn-primary px-3 text-center" %>
    </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class = "container">
    <div class="blog-content mx-auto" style="max-width: 1000px;">

    <div id="<%= dom_id post %>">

      <div class="text-center">
          <%= post.cover_image.present? ? image_tag(post.cover_image, :size => "1000x350") : image_tag("https://via.placeholder.com/50") %>
        </div>
        <div class="badge bg-success-subtle text-success-emphasis mt-3 mb-5 border-bottom border-success rounded border-2 p-2 mb-5">
          <h2><%= post.title %></h2>
      </div>
      <div class="d-flex flex-row mb-4">
        <%= post.user&.profile_picture&.attached? ? image_tag(post.user.profile_picture, size: "60x50", class: "rounded") : image_tag("avatar.png", size: "60x50", class: "rounded-circle") %>

        <footer class="blockquote-footer ms-2 mt-3">
          Author(change its links): <cite title="Source Title"><%= link_to "#{post.user.email.split("@")[0].capitalize}", users_path %></cite>
        </footer>
      </div>
      <div class="d-flex flex-row mb-4" style="max-width: 100%;">
        <div class="d-flex justify-content-start w-100 gap-3">
          <button type="button" class="btn p-0 border-0 bg-transparent">
            <%= image_tag("like_button.png", size: "70x50", class: "rounded-circle") %>
          </button>
          <button type="button" class="btn p-0 border-0 bg-transparent">
            <%= image_tag("like_button.png", size: "70x50", class: "rounded-circle") %>
          </button>
        </div>

        <div class="d-flex justify-content-end w-100 gap-3">
          <button type="button" class="btn p-0 border-0 bg-transparent">
            <%= image_tag("save.png", size: "50x50", class: "rounded-circle") %>
          </button>
          <button type="button" class="btn p-0 border-0 bg-transparent">
            <%= image_tag("share.png", size: "40x35", ) %>
          </button>
          <button type="button" class="btn p-0 border-0 bg-transparent">
            <%= image_tag("more.png", size: "40x35", ) %>
          </button>
        </div>
      </div>



      <div class="mb-5">
           <%= styled_rich_text(post.body, image_height: "200px") %>
        </div>

      </div>


      <p>
        <strong>Status:</strong>
        <%= post.status %>
      </p>

      <p>
        <strong>Category:</strong>
        <%= post.catagory.name %>
      </p>

      <p>
        <strong>Author:</strong>
        <%= post.user.currentuser%>
    </div>
  </div>
</div>

app/views/posts/_post_card.html.erb
<div class="col-sm-4 mb-4">
  <div class="card">
    <div class="card-body">
      <h5 class="card-header"><%= post.title %></h5>
      <p class="card-text"><%= post.overview %></p>
      
      <footer class="blockquote-footer">
        Author: <cite title="Source Title"><%= post.user.email.split("@")[0].capitalize %></cite>
      </footer>

      <%= link_to "Collapse Overview", posts_path, 
                  data: { turbo_frame: "post_frame_#{post.id}" }, 
                  class: "btn btn-secondary" %>
      <%= link_to "Read Blog", post_path(post), class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div class = "container">
  <%= link_to "Show this post", @post , class: "btn btn-secondary mb-2"%> |
  <%= link_to "Back to posts", posts_path , class: "btn btn-secondary mb-2"%>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 mb-4 border-bottom shadow-sm text-center m-5 ">
      <!-- SVG Icon -->
      <div class="d-flex justify-content-around mt-3">
        <a href="#" target="_blank" class="btn btn-link ">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="32" height="32">
            <path d="M12.75 7a.75.75 0 0 0-1.5 0v4.25H7a.75.75 0 0 0 0 1.5h4.25V17a.75.75 0 0 0 1.5 0v-4.25H17a.75.75 0 0 0 0-1.5h-4.25V7Z"></path>
            <path d="M3.75 2A1.75 1.75 0 0 0 2 3.75v16.5c0 .966.784 1.75 1.75 1.75h16.5A1.75 1.75 0 0 0 22 20.25V3.75A1.75 1.75 0 0 0 20.25 2H3.75ZM3.5 3.75a.25.25 0 0 1 .25-.25h16.5a.25.25 0 0 1 .25.25v16.5a.25.25 0 0 1-.25.25H3.75a.25.25 0 0 1-.25-.25V3.75Z"></path>
          </svg>
        </a>
        <!-- Links as Buttons -->
        <%= link_to 'For you', '#', class: 'btn btn-link text-black', style: "font-size: 20px" %>
        <%= link_to 'Following', '#', class: 'btn btn-link text-black', style: "font-size: 20px" %>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-md-9 mb-4">
        <div class="d-flex align-items-center p-3 shadow-sm" style="border: none;">

          <div class="flex-grow-1">
            <div class="d-flex flex-row mb-2">
              <%= post.user&.profile_picture&.attached? ? image_tag(post.user.profile_picture, size: "60x50", class: "rounded") : image_tag("avatar.png", size: "60x50", class: "rounded-circle") %>

              <footer class="blockquote-footer ms-2 mt-3">
                Author(change its links): <cite title="Source Title"><%= link_to "#{post.user.email.split("@")[0].capitalize}", users_path %></cite>
              </footer>
            </div>
            <!-- Blog Text -->

            <h5 class="mb-2 font-weight-bold"><%= post.title %></h5>
            <p class="mb-2 text-muted"><%= truncate(post.overview, length: 150) %></p>

            <%= link_to "Read Blog", post_path(post), class: "btn btn-primary mb-2 mt-3 item justify-content-end" %>
            <br>


          </div>

          <!-- Blog Cover Image -->
          <div class="ml-3">
            <%= post.cover_image.attached? ? image_tag(post.cover_image, size: "250x150") : image_tag("https://via.placeholder.com/50", size: "250x150") %>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/landingpage.html.erb
 
<%=image_tag "blog-img.jpg", class:"img-fluid w-100 d-block", style:"height: 100vh; ", alt:"Landing Image"%>

app/views/posts/new.html.erb
<div class="container">
    <div class = "badge bg-info-subtle text-info-emphasis"> 
      <h1>Add New post</h1>
  </div>
</div>
<br>

<%= render "form", post: @post %>

<br>

<div class = container>
  <%= link_to "Back to posts", posts_path, class: "btn btn-secondary"%>
</div>

<br>

app/views/posts/show.html.erb
<%
=begin%>
<p style="color: green"><%= notice %></p> 
<%
=end%>

<%= render @post %>
<% if user_signed_in? && (current_user.admin? || @post.user == current_user) %>
  <div class= "container mb-5">
    <%= link_to "Edit this post", edit_post_path(@post),  class: "btn btn-secondary mb-2" %> |
    <%= link_to "Back to posts", posts_path, class: "btn btn-secondary mb-2" %>
    <div class="mb-2">
    <%= button_to "Destroy this post", @post, method: :delete, class: "btn btn-danger " %>
    </div>


<%end%>

</div>
<div class="container mb-2">
  <div class="text-center border-success" style="padding: 10px;">
    <h2 class="border-bottom border-success rounded p-3 mb-5" style="display: inline-block;">Comments</h2>
  </div>



  <div class="row">
    <div class="col-sm-6 mb-3 mb-sm-0">
          <%= render @post.comments %>
        </div>
    </div>
    
    <div class="col-sm-6 mb-3 mb-sm-0">
      <div class="card">
        <div class="card-content">
        <h5 class="card-header">Write New Comment</h5>
          <p class="card-text">
            <%= render "comments/form", post: @post %>
          </p>
        </div>
      </div>
    </div>
  </div>