config/routes.rb
# require 'sidekiq/web'
Rails.application.routes.draw do

  # mount Sidekiq::Web => "/sidekiq" # mount Sidekiq::Web in your Rails app

  get 'search', to: 'search#index'

  # config/routes.rb
  resources :subscriptions, only: [:new, :create] do
    post 'pause', on: :member
    post 'resume', on: :member
  end

  devise_for :users
  resources :catagories
  resources :posts
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # 
  resources :posts do
    resources :comments do
      post 'reply', on: :member
    end
  end

  resources :catagories do
    resources :posts
  end

  resources :users do
    resources :posts
  end

  get 'landingpage', to: 'posts#landingpage', as: 'landingpage'

  root to: "posts#index"

  resources :posts do
    member do
      get :expand_overview
    end
  end




end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_footer.html.erb
<footer class="bg-body-tertiary text-center text-lg-start ">
  <!-- Copyright -->
  <div class="text-center p-3 " style="background-color: rgba(0, 0, 0, 0.05);">
    <div class="border-bottom border-secondary" style="display: inline-block;">© 2024 Copyright:
        <a class="text-body" href="#">BlogsWorld</a>
    </div>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= landingpage_path%>">BlogsWorld</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Home", posts_path, class: "nav-link active"%>
        </li>
        <%if user_signed_in?%>
          <li class="nav-item">
          <%= link_to "New blog", new_post_path, class: "nav-link active"%>
          </li>
        <%else%>
            <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <% @catagories.each do |catagory| %>
              <li>
                <a class="dropdown-item" href="<%= catagory_posts_path(catagory) %>">
                  <%= catagory.name %>
                </a>
              </li>
            <% end %>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Authors
          </a>
          <ul class="dropdown-menu">
          <% if @non_admin_users.present? %>
            <% @non_admin_users.each do |user| %>
              <li>
                <a class="dropdown-item" href="<%= user_posts_path(user.id) %>">
                  <%= user.username %>
                </a>
              </li>
            <% end %>
            <% else %>
              <li><a class="dropdown-item" href="#">No authors available</a></li>
            <% end %>
          </ul>
        </li>

        <%end%>
      <%if user_signed_in? && current_user.admin?%>
          <li class="nav-item">
          <%= link_to "View Users", users_path, class: "nav-link active"%>
          </li>
      <%end%>


        

      </ul>
<!--      <form class="d-flex" role="search">-->
<!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--        <button class="btn btn-outline-success" type="submit">Search</button>-->
<!--      </form>-->
      <% unless current_page?(search_path) %>
        <%= button_to 'Search', search_path, method: :get, class: 'btn btn-outline-success' %>
      <% end %>

      <%#= search_form_for @query, url: posts_path, method: :get, class: "d-flex" do |form| %>
        <%#= form.search_field :title_or_overview_or_i_cont_any, class: "form-control me-2", placeholder: "Search", aria: { label: "Search" } %>
        <%#= form.submit "Search", class: "btn btn-outline-success" %>
      <%# end %>


      <%if user_signed_in?%>
        <%= form_with url: destroy_user_session_path, method: :delete, class: "mx-2 d-inline-block" do %>
        <%= submit_tag "Logout", class: "btn btn-outline-success" %>
        2<% end %>

      <%else%>
        <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-success"%>
        </li>
        <li class="nav-item">
          <%= link_to "Login", user_session_path	, class: "btn btn-outline-success"%>
        </li>
      <%end%>

      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogsWorld: Read and Right</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="turbo-refresh-scroll" content="preserve">
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style="height: 100%; margin: 0;">

    <div class="wrapper" style="display: flex; flex-direction: column; min-height: 100vh;">
      <div class="content" style="flex: 1;">
        <%= render "layouts/navbar" %>
        <% unless request.path == landingpage_path %>
          <%= render "layouts/alerts" %>
        <% end %>  

          <%= yield %>
      </div>
        <%= render "layouts/footer" %>
    </div>

    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js', defer: true %>
  </body>
</html>